# Informasi kendaraan
input_merk = '//android.widget.EditText[@hint="Masukkan merk kendaraan"]'
input_jenis = '//android.widget.EditText[@hint="Masukkan jenis kendaraan"]'
input_tahunKendaraan = '//android.widget.EditText[@hint="Masukkan tahun kendaraan"]'
input_noPolisi = '//android.widget.EditText[@hint="Masukkan nomor polisi"]'
input_stnk = '//android.widget.ImageView[@hint="Masukkan nama STNK"]'
input_tglBerakhirSTNK = '//android.view.View[@hint="Pilih tanggal berakhir STNK"]'
btn_okeTanggal = '//android.widget.Button[@content-desc="OKE"]'
input_kilometer = '//android.widget.EditText[@hint="Masukkan odometer\nKilometer"]'
input_warnaUnit = '//android.widget.EditText[@hint="Masukkan warna kendaraan"]'
input_pengajuanPinjaman = '//android.widget.EditText[@hint="Rp\nMasukkan jumlah pinjaman"]'

# Informasi data nasabah
input_alamatDomisili = '//android.widget.EditText[@hint="Masukkan alamat domisili"]'
checkbox_sesuaiKTP = '//android.widget.CheckBox'
input_kepemilikan = '//android.widget.Button[@content-desc="Pilih kepemilikan"]'
btn_milikSendiri = '//android.widget.Button[@content-desc="Milik Sendiri"]'
input_buktiKepemilikan = '//android.widget.Button[@content-desc="Pilih bukti kepemilikan"]'
btn_SHM = '//android.widget.Button[@content-desc="Sertifikat Hak Milik (SHM)"]'
input_kondisiRumah = '//android.widget.EditText[@hint="Masukkan kondisi rumah"]'
input_kondisiLingkungan = '//android.widget.EditText[@hint="Masukkan kondisi lingkungan"]'
input_aksesJalan = '//android.widget.EditText[@hint="Masukkan akses jalan"]'
input_lamaTinggal = '//android.widget.EditText[@hint="Masukkan lama tinggal\nTahun"]'
input_pilihGarasi = '//android.widget.Button[@content-desc="Pilih status garasi"]'
status_garasiAda = '//android.widget.Button[@content-desc="Ada"]'

# Informasi Usaha/Pekerjaan
input_namaUsaha = '//android.widget.EditText[@hint="Masukkan nama usaha"]'
input_alamatUsaha = '//android.widget.EditText[@hint="Masukkan alamat usaha"]'
input_jabatan = '//android.widget.EditText[@hint="Masukkan jabatan"]'
input_noTelpUsaha = '//android.widget.EditText[@hint="Masukkan nomor telepon usaha"]'
input_statusUsaha = '//android.widget.EditText[@hint="Masukkan status usaha"]'
input_lamaUsaha = '//android.widget.EditText[@hint="Masukkan lama usaha\nTahun"]'
input_omsetMinimal = '//android.widget.EditText[@hint="Rp\nMinimal"]'
input_omsetMaksimal = '//android.widget.EditText[@hint="Rp\nMaksimal"]'
input_izinUsaha = '//android.widget.Button[@content-desc="Pilih izin usaha"]'
btn_tidakAda = '//android.widget.Button[@content-desc="Tidak Ada"]'
input_bidangUsaha = '//android.widget.EditText[@hint="Masukkan bidang usaha"]'
input_karyawanMinimal = '//android.widget.EditText[@hint="Minimal"]'
input_karyawanMaximal = '//android.widget.EditText[@hint="Maksimal"]'
checkbox_seluruhDataFidusia = '//android.view.View[@content-desc="PERNYATAAN Seluruh data yang dituliskan dan terlampir dalam pengajuan ini adalah benar"]/android.widget.CheckBox[1]'
checkbox_sayaMembacaFidusia = '//android.view.View[@content-desc="PERNYATAAN Seluruh data yang dituliskan dan terlampir dalam pengajuan ini adalah benar"]/android.widget.CheckBox[2]'
btn_proses = '//android.view.View[@content-desc="Proses"]'

btn_selesaiFidusia = '//android.widget.ImageView[@content-desc="Pengajuan Gadai BPKB Fidusia\nPengajuan Gadai BPKB Fidusia Anda telah kami terima. Kami akan segera menghubungi Anda untuk proses selanjutnya\nSelesai"]'
